name: nibjobs
description: Ethiopian job finder
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.4
  cached_network_image: ^3.1.0
  platform_device_id: ^1.0.1
  flutter_spinkit: ^5.1.0
  firebase_auth: "^3.1.2"
  cloud_firestore: "^2.5.2"
  google_sign_in: "^5.2.1"
  firebase_core: "^1.6.0"
  firebase_storage: "^10.0.3"
  material_tag_editor: ^0.1.1
  firebase_analytics: "^8.3.2"
  firebase_messaging: "^10.0.7"
  flutter_local_notifications: ^8.2.0
  firebase_dynamic_links: ^2.0.9
  rxdart: ^0.27.2
  flutter_signin_button: ^2.0.0
  flutter_rating_bar: 4.0.0
  auto_size_text: ^3.0.0
  url_launcher: ^6.0.12
  dio: ^4.0.0
  equatable: ^2.0.0
  bloc: ^7.0.0
  flutter_bloc:
  connectivity_plus: ^1.1.0
  image_picker: ^0.8.4
  uuid: ^3.0.0
  awesome_dialog: ^2.1.0
  sign_in_with_apple: ^3.2.0
  crypto: ^3.0.0
  carousel_slider: ^4.0.0
  shimmer: ^2.0.0
  pull_to_refresh: ^2.0.0
  timeago: ^3.1.0
  infinite_widgets: ^2.0.0
  share: ^2.0.4
  mime: ^1.0.1
  infinite_scroll_pagination: ^3.1.0
  device_preview: ^0.7.4
  flutter_screenutil: ^5.0.0+2
  fluttertoast: ^8.0.8
  intl_phone_field: ^2.1.0
  google_mobile_ads: ^0.13.6
  flutter_staggered_grid_view: ^0.4.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/apply_for_job.png
    - assets/images/create_job.png
    - assets/images/make_money.png
    - assets/images/select_language.png
    - assets/images/signup.png
    - assets/images/default_avatar.png


  fonts:
    - family: Sofia
      fonts:
        - asset: assets/fonts/Sofia-Pro-Regular.ttf
          weight: 700
    - family: Noto
      fonts:
        - asset: assets/fonts/NotoSansEthiopic-Bold.ttf

    - family: NibCustomIcons
      fonts:
        - asset: assets/icons/NibCustomIcons.ttf
